### ISSUE TITLE
可以在这里膜yh吗/kk

### ISSUE THREAD

**Issue by Officeyutong** [kernelbin/OI_FansGroup#2]
如题/kk
![T%CHY6M_5D}M00PS8Y7{NOE](https://user-images.githubusercontent.com/9004058/82062014-0d764080-96fc-11ea-9070-d4c092e1fb86.jpg)
![_NZ7Z%F{HS}51KV M(7Z59](https://user-images.githubusercontent.com/9004058/82062041-17983f00-96fc-11ea-8f55-04349876c059.png)

**Comment by kernelbin** [comment]
不可以，但是你可以在mnfe粉丝群里自己%自己/kk
