### ISSUE TITLE
Cannot find group

### ISSUE THREAD

**Issue by undefined-moe** [kernelbin/OI_FansGroup#3]
https://github.com/kernelbin/OI_FansGroup/blob/master/kernel.bin/README.md

**Comment by CoelacanthusHex** [comment]
我记得好像被解散了（

**Comment by kernelbin** [comment]
I‘ve already left that group because I'm too vegetable😭
I don't know what happened after that but I guess it's already dismissed...
I will remove it from this repo soon.
